### ISSUE TITLE
Game not working help plz

### ISSUE THREAD

**Issue by Shm00lik** [NiranSchneller/agar.py#1]
Hello I'm trying to play this game but it is not working.
Can you help me plz?

Also, have you heard of Slither.py? I found the project to be fantastic, like this one...

**Comment by NiranSchneller** [comment]
Hey :)

Can you please be more specific? what isn't working?
also, looked at the repository, looks like a great start, can't wait to see how it develops

**Comment by Shm00lik** [comment]
Yeah sure
Basically I tried to run the game via CMD but it shows the following message:
"Your computer has a virus"
Waht can I do?

plz help I want to play the game a lot

**Comment by NiranSchneller** [comment]
ok so I see what's happening, I think the problem you have is beyond that.
call tech support or smthn

good luck!

**Comment by Shm00lik** [comment]
# ok thank you sir

###### ophir you should give him 100
